# Postgre baasist andmete pärimine

In [5]:
!pip3 install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp39-cp39-macosx_11_0_arm64.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 3.6 MB/s eta 0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [12]:
!pip3 install requests

Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 1.3 MB/s eta 0:00:011
Collecting certifi>=2017.4.17
  Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 2.2 MB/s eta 0:00:01
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 3.6 MB/s eta 0:00:01
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 3.2 MB/s eta 0:00:01
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl (299 kB)
     |████████████████████████████████| 299 kB 3.0 MB/s eta 0:00:01
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2026.2.25 charset-normalizer-3.4.7 idna-3.11 requests-2.32.5 urllib3-2.6.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [9]:
!pip3 install lxml

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.0.3-cp39-cp39-macosx_10_9_universal2.whl (8.6 MB)
     |████████████████████████████████| 8.6 MB 3.0 MB/s eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.0.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

# Andmete lugemine veebi APIst JSON kujul

In [10]:
import requests
import pandas as pd
import psycopg2

In [ ]:
response = requests.get("https://jsonplaceholder.typicode.com/posts")
response

In [ ]:
response.json()[:3]

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

In [7]:
df = pd.DataFrame(response.json())
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [ ]:
pd.DataFrame([{'userId': 1,
  'id': 1,
  'title': 'sunt aut',
  'body': 'quia et suscipit'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi '}]
)

   userId  id                title              body
0       1   1             sunt aut  quia et suscipit
1       1   2         qui est esse         est rerum
2       1   3  ea molestias quasi                NaN

## Vigade haldus

In [13]:
try:
    conn = psycopg2.connect(
        host="localhost",
        database="mydb",
        user="user",
        password="password"
    )

    df = pd.read_sql("SELECT * FROM customers WHERE active = true", conn)
    conn.close()
except:
    print("Oi kui kahju, andmebaasi pole, otsisin igalt poolt aga ikka ei leidnud...")

Oi kui kahju, andmebaasi pole, otsisin igalt poolt aga ikka ei leidnud...

In [ ]:
countries = ["Estonia", "Latvia", "Lithuania"]

try:
    fourth_country = countries[3]
    print(fourth_country)
except IndexError:
    print("No forth country...")
except ValueError:
    pass
except:
    print("Oi oi, täiesti ootamatu viga, mis nüüd küll saab!")

No forth country...

In [ ]:
def numeric_year(year_str: str) -> int:
    """
    Convert a year in format "2025 A.D." or "2025 B.C." to numeric.
    """
    # Ensure input has two components corresponding to year and era
    try:
        year_number_str, year_era_notation_str = year_str.split(" ")
    except:
         raise ValueError(f"'{year_str}' is not a valid year number: exactly two components expected")
    
    # Ensure year number is numeric
    try:
        year_numeric = int(year_number_str)
    except:
         raise ValueError(f"'{year_str}' is not a valid year number: year not numeric ")
    
    # Determin sign based on era identifier
    if year_era_notation_str == "A.D.":
        return year_numeric
    if year_era_notation_str == "B.C.":
        return -year_numeric
    raise ValueError(f"'{year_str}' is not a valid year number: unknown era")

print(numeric_year("2024 A.D.")) # 2024
print(numeric_year("1 B.C.")) # -1
print(numeric_year("12 A.D.")) # 12
# print(numeric_year("KaksteisA.D.")) # 12

2024
-1
12

In [22]:
"2024 A.D".split(" ")

['2024', 'A.D']

In [21]:
era = "A.D."

if era == "A.D.":
    print("Christ!")
else:
    print("Not yet Christ!")

Christ!